name: EasyOptimised
version: '1.0-SNAPSHOT'
main: me.idroom1.easyoptimised.EasyOptimised
api-version: '1.20'
commands:
  killall:
    description: Kills all entities in the world
    usage: /killall entities

